# A useful makefile which factors names and flags into make variables
# so the rules can be as generic as possible
# $@ is make's built-in variable for the target (left of :)
# $^ is make's built-in variable for the prereqs (right of :)
# $< is make's built-in variable for the first item in the prereqs

CC=gcc
CFLAGS=-g
OBJS=hello.o
EXECUTABLE=hello

$(EXECUTABLE): $(OBJS)
	$(CC) $(CFLAGS) -o $(EXECUTABLE) $^

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -rf $(EXECUTABLE) $(OBJS)

